#!/usr/bin/env bash
#
# Provision and start a pinned Jellyfin 12.0.0 test host on this Alpine/musl
# system (amd64, non-root), for the ArrTags testing/release verification tasks.
#
# Usage:
#   scripts/provision-jellyfin-test-host.sh [PREFIX]
#
# PREFIX defaults to /tmp/arrtags-jellyfin. The script is idempotent: it
# downloads and extracts only what is missing, then (re)starts the host and
# waits for its public system endpoint.
#
# It requires network access to repo.jellyfin.org and dl-cdn.alpinelinux.org.
# The host is a test fixture only; nothing here is shipped with the plugin.

set -euo pipefail

PREFIX="${1:-/tmp/arrtags-jellyfin}"
PACKAGES_DIR="${PREFIX}/apks"
SYSROOT="${PREFIX}/sysroot/root"
HOST_DIR="${PREFIX}/jellyfin"
DATA_DIR="${PREFIX}/data"
CONFIG_DIR="${PREFIX}/config"
CACHE_DIR="${PREFIX}/cache"
LOG_DIR="${PREFIX}/log"
FFCACHE_DIR="${PREFIX}/fccache"
CONSOLE_LOG="${PREFIX}/console.log"
PORT="${JELLYFIN_PORT:-8096}"

JELLYFIN_TARBALL_URL="https://repo.jellyfin.org/files/server/linux/stable/v12.0/amd64-musl/jellyfin_12.0-amd64-musl.tar.gz"

echo "==> ArrTags Jellyfin 12.0.0 musl test host"
echo "    prefix: ${PREFIX}"

# --- 1. Extract the pinned Jellyfin 12.0.0 amd64-musl server -----------------
mkdir -p "${PREFIX}" "${PACKAGES_DIR}" "${SYSROOT}" "${DATA_DIR}" "${CONFIG_DIR}" "${CACHE_DIR}" "${LOG_DIR}" "${FFCACHE_DIR}"

if [ ! -x "${HOST_DIR}/jellyfin" ]; then
    echo "==> Downloading Jellyfin 12.0.0 amd64-musl server"
    curl -fsSL --retry 3 -o "${PREFIX}/jellyfin.tar.gz" "${JELLYFIN_TARBALL_URL}"
    tar -xzf "${PREFIX}/jellyfin.tar.gz" -C "${PREFIX}"
    chmod +x "${HOST_DIR}/jellyfin"
else
    echo "==> Jellyfin server already extracted"
fi

# --- 2. Extract the Alpine runtime libraries the server needs ----------------
# Skia needs fontconfig; the server needs real ICU (invariant globalization is
# rejected by Jellyfin's Startup because it requires the en-US culture); and the
# server refuses to start when no FFmpeg is found in $PATH. Alpine's ffmpeg
# additionally needs libpulsecommon from the libpulse package.
ALPINE_PACKAGES="fontconfig icu-libs icu-data-full ffmpeg"

if [ ! -f "${SYSROOT}/usr/bin/ffmpeg" ] || [ ! -f "${SYSROOT}/usr/share/icu/78.1/icudt78l.dat" ]; then
    echo "==> Fetching Alpine runtime packages: ${ALPINE_PACKAGES}"
    ( cd "${PACKAGES_DIR}" && apk fetch --no-cache -R -o . ${ALPINE_PACKAGES} )
    for apk in "${PACKAGES_DIR}"/*.apk; do
        tar -xzf "${apk}" -C "${SYSROOT}" 2>/dev/null || true
    done
else
    echo "==> Alpine runtime packages already extracted"
fi

# --- 3. Stop any previous instance and free the port ------------------------
# Match on the process comm rather than pgrep -x: a killed-but-unreaped Jellyfin
# can be reported inconsistently by pgrep, and the launcher execs the managed app
# with comm "jellyfin".
for proc in /proc/[0-9]*; do
    if [ "$(cat "${proc}/comm" 2>/dev/null)" = "jellyfin" ]; then
        kill -9 "${proc#/proc/}" 2>/dev/null || true
    fi
done

port_in_use() {
    (ss -ltn 2>/dev/null || netstat -ltn 2>/dev/null) | grep -q ":${PORT} "
}

for _ in $(seq 1 20); do
    port_in_use || break
    sleep 1
done
if port_in_use; then
    echo "ERROR: port ${PORT} is still in use; a stale Jellyfin process may be holding it." >&2
    exit 1
fi

# --- 4. Write the launcher ---------------------------------------------------
START_SCRIPT="${PREFIX}/start-jellyfin.sh"
cat > "${START_SCRIPT}" <<EOF
#!/bin/bash
# Generated by scripts/provision-jellyfin-test-host.sh
export LD_LIBRARY_PATH="${SYSROOT}/usr/lib:${SYSROOT}/usr/lib/pulseaudio:${SYSROOT}/lib:/config/sysroot/usr/lib:\${LD_LIBRARY_PATH:-}"
export FONTCONFIG_PATH="${SYSROOT}/etc/fonts"
export XDG_CACHE_HOME="${FFCACHE_DIR}"
export ICU_DATA="${SYSROOT}/usr/share/icu/78.1/"
export PATH="${SYSROOT}/usr/bin:\$PATH"
# Jellyfin requires real cultures (en-US); do NOT enable invariant globalization.
unset DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
cd "${HOST_DIR}"
exec ./jellyfin \\
    --datadir "${DATA_DIR}" \\
    --configdir "${CONFIG_DIR}" \\
    --cachedir "${CACHE_DIR}" \\
    --logdir "${LOG_DIR}" \\
    --nowebclient \\
    --ffmpeg "${SYSROOT}/usr/bin/ffmpeg"
EOF
chmod +x "${START_SCRIPT}"

# --- 5. Start and wait for the public system endpoint ------------------------
echo "==> Starting Jellyfin (port ${PORT}); logs: ${CONSOLE_LOG}"
nohup "${START_SCRIPT}" > "${CONSOLE_LOG}" 2>&1 &

for _ in $(seq 1 60); do
    if grep -q "Startup complete" "${CONSOLE_LOG}" 2>/dev/null \
        && curl -fsS --max-time 3 "http://127.0.0.1:${PORT}/System/Info/Public" >/dev/null 2>&1; then
        echo "==> Jellyfin is up:"
        curl -fsS "http://127.0.0.1:${PORT}/System/Info/Public"
        echo
        echo "    datadir:   ${DATA_DIR}"
        echo "    configdir: ${CONFIG_DIR}"
        echo "    plugins:   ${DATA_DIR}/plugins"
        echo "    cachedir:  ${CACHE_DIR}"
        echo "    logdir:    ${LOG_DIR}"
        exit 0
    fi
    sleep 3
done

echo "ERROR: Jellyfin did not become ready. Last console output:" >&2
tail -40 "${CONSOLE_LOG}" >&2
exit 1
